trigger:
  - main

pr: none

jobs:
  - job: 'Push_to_github'
    timeoutInMinutes: 30
    pool:
      vmImage: macOS-15
    variables:
      - group: aapp_testing_e2e
    steps:
      - template: ./templates/push-repo-to-github.yml
        parameters:
          repository: 'amsterdam-app-e2e'
          sshKeySecureFile: 'e2e-github-ssh'
          sshPublicKey: $(sshPublicKeyE2e)
