trigger:
- main

parameters:
  - name: iosAppId
    displayName: 'Existing iOS App ID (optional)'
    type: string
    default: ' '
  - name: testSuiteId
    displayName: 'Existing Test Suite ID (optional)'
    type: string
    default: ' '

resources:
  pipelines:
    - pipeline: build
      source: 'aapp_app_mobile [build]'
      trigger:
        branches:
          include:
            - main

schedules:
  - cron: "0 0 * * *"   # every night
    displayName: Scheduled E2E Test
    branches:
      include:
        - main
    always: true  # run even if no recent changes

variables:
  - group: aapp_testing_e2e

pool:
  vmImage: 'macOS-15'

steps:
- powershell: |
    $devices = @(
      "iPhone 16 Pro Max-18.0"
      "iPhone 15-17.0"
      "iPhone SE 2020-16.0"
    )
    $random = Get-Random -Minimum 0 -Maximum $devices.Length
    $randomDevice = $devices[$random]
    Write-Host "##vso[task.setvariable variable=randomDevice]$randomDevice"
  displayName: 'Pick random device'

- template: templates/shared.yml
  parameters:
    appId: ${{ parameters.iosAppId }}
    testSuiteId: ${{ parameters.testSuiteId }}
    buildArtifact: 'ios-build'
    appFileName: 'ios/builds/AmsterdamTest.ipa'
    platform: 'ios'
    device: $(randomDevice)
    buildApiUrl: 'https://api-cloud.browserstack.com/app-automate/maestro/v2/ios/build'
